# -*- coding: utf-8 -*-
"""NLP_NLI_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/MrBIue/Le-Minh-Thuan-NLP-NLI-TTNTK46-4654100012/blob/main/NLP_NLI_Final.ipynb
"""

#1 Cài đặt thư viện
!pip install -q transformers datasets evaluate accelerate scikit-learn

#2 Tải dữ liệu và chia tỷ lệ 80/10/10 chuẩn Zero-shot
from datasets import load_dataset

print("Đang tải dữ liệu...")
# 1. Tải MultiNLI (Tiếng Anh)
mnli = load_dataset("multi_nli")
# 2. Tải XNLI (Phân vùng Tiếng Việt)
xnli = load_dataset("xnli", "vi")

# --- CHIA TỶ LỆ 80/10/10 ---
# MNLI gốc có gần 400k mẫu, Colab miễn phí sẽ không chạy nổi.
# Ta lấy một tập con (subset) đại diện theo tỷ lệ 16000 : 2000 : 2000

# TRAIN (80%): 16000 mẫu tiếng Anh
train_dataset = mnli["train"].shuffle(seed=42).select(range(16000))

# VALIDATION (10%): 2000 mẫu tiếng Anh (MNLI dùng tên 'validation_matched')
val_dataset = mnli["validation_matched"].shuffle(seed=42).select(range(2000))

# TEST (10%): 2000 mẫu tiếng Việt
test_dataset = xnli["test"].shuffle(seed=42).select(range(2000))

print(f"Số lượng Train (Tiếng Anh): {len(train_dataset)}")
print(f"Số lượng Validation (Tiếng Anh): {len(val_dataset)}")
print(f"Số lượng Test (Tiếng Việt): {len(test_dataset)}")

#3 Tiền xử lý với XLM-RoBERTa
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_name = "xlm-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Khởi tạo mô hình phân loại 3 nhãn (Entailment, Neutral, Contradiction)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=3)

def preprocess_function(examples):
    # XLM-R sẽ tự động chèn token [SEP] giữa premise và hypothesis
    return tokenizer(
        examples["premise"],
        examples["hypothesis"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

print("Đang mã hóa dữ liệu (Tokenization)...")
# Tokenize tập Anh
tokenized_train = train_dataset.map(preprocess_function, batched=True)
tokenized_val = val_dataset.map(preprocess_function, batched=True)
# Tokenize tập Việt
tokenized_test = test_dataset.map(preprocess_function, batched=True)

# Lên danh sách các cột thừa có thể có
potential_cols_mnli = ["promptID", "pairID", "premise", "hypothesis", "premise_binary_parse", "premise_parse", "hypothesis_binary_parse", "hypothesis_parse", "genre"]
potential_cols_xnli = ["premise", "hypothesis", "language"]

# TỰ ĐỘNG LỌC: Chỉ xóa những cột thực sự tồn tại trong dataset hiện tại
cols_to_remove_mnli = [col for col in potential_cols_mnli if col in tokenized_train.column_names]
cols_to_remove_xnli = [col for col in potential_cols_xnli if col in tokenized_test.column_names]

# Thực hiện xóa cột thừa
tokenized_train = tokenized_train.remove_columns(cols_to_remove_mnli)
tokenized_val = tokenized_val.remove_columns(cols_to_remove_mnli)
tokenized_test = tokenized_test.remove_columns(cols_to_remove_xnli)

# Đổi tên cột 'label' thành 'labels' cho đúng chuẩn đầu vào của PyTorch Trainer
tokenized_train = tokenized_train.rename_column("label", "labels")
tokenized_val = tokenized_val.rename_column("label", "labels")
tokenized_test = tokenized_test.rename_column("label", "labels")

print("Tiền xử lý hoàn tất! Các cột hiện tại của tập Test:", tokenized_test.column_names)

#4 Thiết lập Huấn luyện
import numpy as np
import evaluate
from transformers import TrainingArguments, Trainer

# Hàm tính toán độ chính xác
metric = evaluate.load("accuracy")
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

# Cấu hình tham số huấn luyện (Đã cập nhật theo API mới nhất)
training_args = TrainingArguments(
    output_dir="./xlmr_nli_model",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    fp16=True,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    processing_class=tokenizer,       # ĐÃ SỬA TẠI ĐÂY: Đổi từ tokenizer thành processing_class
    compute_metrics=compute_metrics
)

# BẮT ĐẦU HUẤN LUYỆN
print("Bắt đầu quá trình Fine-tuning...")
trainer.train()

#5 Đánh giá Zero-shot trên Tiếng Việt
print("==================================================")
print("BẮT ĐẦU ĐÁNH GIÁ ZERO-SHOT TRÊN TẬP XNLI TIẾNG VIỆT")
print("==================================================")

# Yêu cầu mô hình (chỉ mới học tiếng Anh) làm bài thi tiếng Việt
test_results = trainer.evaluate(eval_dataset=tokenized_test)

print(f"Độ chính xác (Accuracy) trên tiếng Việt: {test_results['eval_accuracy'] * 100:.2f}%")

#6 Vẽ Ma trận nhầm lẫn
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix

print("Đang trích xuất dự đoán chi tiết trên tập Test (Tiếng Việt)...")
# Lấy dự đoán từ mô hình
predictions_output = trainer.predict(tokenized_test)
y_pred = np.argmax(predictions_output.predictions, axis=1)
y_true = predictions_output.label_ids

# Tên các nhãn
target_names = ['Entailment', 'Neutral', 'Contradiction']

# 1. In báo cáo F1-Score, Precision, Recall
print("\n--- BÁO CÁO PHÂN LOẠI CHI TIẾT ---")
print(classification_report(y_true, y_pred, target_names=target_names))

# 2. Vẽ biểu đồ Ma trận nhầm lẫn (Confusion Matrix)
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=target_names, yticklabels=target_names)
plt.xlabel('Dự đoán của Mô hình (Predicted)')
plt.ylabel('Nhãn thực tế (True)')
plt.title('Ma trận nhầm lẫn trên tập XNLI (Tiếng Việt)')
#plt.show()